// react-chat/src/App.tsx
import { useState, useEffect } from 'react';
import io from 'socket.io-client';
import Message from './Message';

const socket = io('http://localhost:3001');

export interface Message {
  content: string;
  username?: string;
  room?: string;
}

function App() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [messageText, setMessageText] = useState('');


  useEffect(() => {
    socket.on('connect', () => {
      setMessages([...messages, { content: `You connected with id: ${socket.id}` }]);
      localStorage.setItem("user", "jani")
    })

    socket.on('recieve-message', (message: Message) => {
      setMessages([...messages, message]);
    });

    socket.on('connect_error', (err) => {
      setMessages([...messages, { content: err.message }])
    });

    socket.on('user-joined', (data: any) => {
      setMessages([...messages, { content: `${data.id} joined` }])
    });
  }, [messages]);

  const sendMessage = () => {
    socket.emit('send-message', { content: messageText });
    setMessages([...messages, { content: messageText }]);
    setMessageText('');
  };

  return (
    <div className="App">
      <h1>Real-Time Chat App</h1>
      <div className="messages">
        {messages.map((message, index) => (
          <Message key={index} username={message.username} content={message.content} />
        ))}
      </div>
      <div className="input-box">
        <input
          type="text"
          value={messageText}
          onChange={(e) => setMessageText(e.target.value)}
          placeholder="Type your message..."
        />
        <button onClick={sendMessage}>Send</button>
      </div>
    </div>
  );
}

export default App;

// chat-client/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { io } from 'socket.io-client';
import { Message } from '../models/message.model';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent implements OnInit {
  socket = io('ws://localhost:3000');

  title = 'chat-client';
  messages: Message[] = [];

  roomInput!: string;
  messageInput!: string;

  sendMessage() {
    if (!this.messageInput?.trim()) return;

    this.messages.push({ content: this.messageInput });
    this.socket.emit('message', this.assembleMessageData());
    this.messageInput = '';
  }

  ngOnInit() {
    this.socket.on('connect', () => {
      this.messages.push({
        content: `You connected with id: ${this.socket.id}`,
      });
    });

    this.socket.on('message', (data: Message) => {
      this.messages.push(data);
    });
  }

  private assembleMessageData(): Message {
    return {
      content: this.messageInput,
    };
  }
}

<div id="messageBox">
  @for (message of messages; track $index) {
  <p>{{ message.content }}</p>
  }
</div>

<form>
  <input
    type="text"
    id="messageInput"
    placeholder="message"
    name="message"
    [(ngModel)]="messageInput"
  /><br />
  <input
    type="text"
    id="roomInput"
    placeholder="Room"
    name="room"
    [(ngModel)]="roomInput"
  /><br />
  <input type="submit" value="Send" (click)="sendMessage()" />
</form>

<router-outlet />
